-- =======================================================
-- EVENT MANAGEMENT SYSTEM DATABASE SETUP AND QUERIES
-- =======================================================

-- 1. Create Tables (Schema Definition)
-------------------------------------------------------

CREATE TABLE Users (
    user_id INT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    city VARCHAR(100),
    age INT,
    CHECK (age >= 18)
);

CREATE TABLE Events (
    event_id INT PRIMARY KEY,
    event_name VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL,
    ticket_price DECIMAL(10, 2) NOT NULL DEFAULT 0.00
);

CREATE TABLE Registrations (
    registration_id INT PRIMARY KEY,
    user_id INT NOT NULL,
    event_id INT NOT NULL,
    registration_date DATE NOT NULL, 
    feedback_rating INT, 
    attended BOOLEAN NOT NULL,
    
    FOREIGN KEY (user_id) REFERENCES Users(user_id),
    FOREIGN KEY (event_id) REFERENCES Events(event_id),
    
    CHECK (feedback_rating IS NULL OR (feedback_rating >= 1 AND feedback_rating <= 10))
);

-- 2. Insert Sample Data (CRUD: Create)
-------------------------------------------------------

-- Insert 6 Users
INSERT INTO Users (user_id, name, city, age) VALUES
(101, 'Alice Smith', 'New York', 28),
(102, 'Bob Johnson', 'Los Angeles', 45),
(103, 'Charlie Brown', 'New York', 22),
(104, 'Diana Prince', 'San Francisco', 35), -- Diana's city updated earlier
(105, 'Eve Adams', 'Los Angeles', 50);
-- User 106 (Frank Miller) and related registration were deleted in the example CRUD.

-- Insert 5 Events
INSERT INTO Events (event_id, event_name, category, ticket_price) VALUES
(201, 'Tech Summit 2025', 'Technology', 150.00),
(202, 'Jazz Night Live', 'Music', 75.50),
(203, 'Gourmet Food Festival', 'Food', 50.00),
(204, 'Web Dev Workshop', 'Technology', 150.00),
(205, 'City Marathon', 'Sports', 30.00); -- Price updated earlier

-- Insert 11 Registrations
INSERT INTO Registrations (registration_id, user_id, event_id, registration_date, feedback_rating, attended) VALUES
(301, 101, 201, '2025-01-10', 9, TRUE),
(302, 101, 202, '2025-01-15', 8, TRUE),
(303, 102, 201, '2025-02-01', 7, TRUE),
(304, 103, 203, '2025-02-05', 10, TRUE),
(305, 104, 204, '2025-02-10', NULL, FALSE),
(306, 105, 205, '2025-02-12', 6, TRUE),
(307, 101, 203, '2025-02-15', 9, TRUE),
(308, 102, 202, '2025-02-20', 7, TRUE),
(310, 104, 205, '2025-03-01', NULL, FALSE),
(311, 103, 202, '2025-03-05', 9, TRUE),
(312, 105, 201, '2025-03-06', NULL, TRUE); -- Added a new registration for Eve

-- 3. Analytical Queries
-------------------------------------------------------

-- Q1: Event Popularity (Total Registrations)
SELECT 
    E.event_name,
    COUNT(R.registration_id) AS total_registrations
FROM Events E
JOIN Registrations R ON E.event_id = R.event_id
GROUP BY E.event_name
ORDER BY total_registrations DESC;

-- Q2: Total Registrations and Average Feedback for Each Event
SELECT 
    E.event_name,
    COUNT(R.registration_id) AS total_registrations,
    ROUND(AVG(R.feedback_rating), 2) AS average_rating
FROM Events E
LEFT JOIN Registrations R ON E.event_id = R.event_id
GROUP BY E.event_name
ORDER BY average_rating DESC NULLS LAST;

-- Q3: Find events with an average rating greater than 8
SELECT 
    E.event_name,
    ROUND(AVG(R.feedback_rating), 2) AS average_rating
FROM Events E
JOIN Registrations R ON E.event_id = R.event_id
WHERE R.feedback_rating IS NOT NULL
GROUP BY E.event_name
HAVING AVG(R.feedback_rating) > 8
ORDER BY average_rating DESC;

-- Q4: Determine total revenue generated by each event
SELECT 
    E.event_name,
    (COUNT(R.registration_id) * E.ticket_price) AS total_revenue
FROM Events E
JOIN Registrations R ON E.event_id = R.event_id
GROUP BY E.event_name, E.ticket_price
ORDER BY total_revenue DESC;

-- Q5: Identify top-performing events in each category (based on Average Rating)
WITH CategoryRatings AS (
    SELECT
        E.event_name,
        E.category,
        ROUND(AVG(R.feedback_rating), 2) AS average_rating,
        ROW_NUMBER() OVER (PARTITION BY E.category ORDER BY AVG(R.feedback_rating) DESC) AS rn
    FROM Events E
    JOIN Registrations R ON E.event_id = R.event_id
    WHERE R.feedback_rating IS NOT NULL
    GROUP BY E.event_name, E.category
)
SELECT 
    event_name,
    category,
    average_rating
FROM CategoryRatings
WHERE rn = 1;

-- Q6: Display users who attended more than one event
SELECT 
    U.name,
    COUNT(R.registration_id) AS events_attended
FROM Users U
JOIN Registrations R ON U.user_id = R.user_id
WHERE R.attended = TRUE
GROUP BY U.name
HAVING COUNT(R.registration_id) > 1
ORDER BY events_attended DESC;

-- Q7: Show users who have not attended any event
SELECT 
    U.name
FROM Users U
LEFT JOIN Registrations R ON U.user_id = R.user_id
GROUP BY U.user_id, U.name
HAVING SUM(CASE WHEN R.attended = TRUE THEN 1 ELSE 0 END) = 0;

-- Q8: Retrieve users who attended the most expensive event
SELECT 
    U.name,
    E.event_name
FROM Users U
JOIN Registrations R ON U.user_id = R.user_id
JOIN Events E ON R.event_id = E.event_id
WHERE R.attended = TRUE
  AND E.ticket_price = (SELECT MAX(ticket_price) FROM Events);

-- Q9: Generate a leaderboard showing each user’s total attended events and average rating
SELECT
    U.name,
    COUNT(CASE WHEN R.attended = TRUE THEN 1 END) AS total_attended_events,
    ROUND(AVG(CASE WHEN R.attended = TRUE THEN R.feedback_rating END), 2) AS average_rating_attended
FROM Users U
LEFT JOIN Registrations R ON U.user_id = R.user_id
GROUP BY U.name
ORDER BY total_attended_events DESC, average_rating_attended DESC NULLS LAST;
-- END OF ASSIGNMENT CODE

-- Extra things 

-- 1: Add Indexes for Faster Queries

-- Index for quickly finding registrations by user
CREATE INDEX idx_registrations_user
ON Registrations(user_id);

-- Index for quickly finding registrations by event
CREATE INDEX idx_registrations_event
ON Registrations(event_id);

-- Index on city for user demographic queries
CREATE INDEX idx_users_city
ON Users(city);

-- Index on category for event filtering
CREATE INDEX idx_events_category
ON Events(category);

--2 : Organizers table for event ownership

CREATE TABLE Organizers (
    organizer_id INT PRIMARY KEY,
    organizer_name VARCHAR(150) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL
);

-- Update Events to connect with Organizer
ALTER TABLE Events
ADD COLUMN organizer_id INT;

ALTER TABLE Events
ADD FOREIGN KEY (organizer_id) 
REFERENCES Organizers(organizer_id);

-- Sample Organizers
INSERT INTO Organizers (organizer_id, organizer_name, email) VALUES
(1, 'Global Tech Inc', 'contact@globaltech.com'),
(2, 'SoundWave Media', 'info@soundwave.com'),
(3, 'City Sports Club', 'events@citysports.com');

-- Update events to assign organizers
UPDATE Events SET organizer_id = 1 WHERE event_id IN (201, 204);
UPDATE Events SET organizer_id = 2 WHERE event_id IN (202);
UPDATE Events SET organizer_id = 3 WHERE event_id IN (205);
UPDATE Events SET organizer_id = 1 WHERE event_id IN (203);


-- Function: Get average rating of any event by event_id
CREATE FUNCTION GetEventAverageRating(e_id INT)
RETURNS DECIMAL(5,2)
DETERMINISTIC
BEGIN
    DECLARE avg_rating DECIMAL(5,2);

    SELECT ROUND(AVG(feedback_rating),2)
    INTO avg_rating
    FROM Registrations
    WHERE event_id = e_id 
      AND feedback_rating IS NOT NULL;

    RETURN avg_rating;
END;


-- Stored Procedure to get event summary
CREATE PROCEDURE GetEventSummary(IN e_id INT)
BEGIN
    SELECT 
        E.event_name,
        E.category,
        E.ticket_price,
        (SELECT COUNT(*) FROM Registrations WHERE event_id = e_id) AS total_registrations,
        GetEventAverageRating(e_id) AS average_rating;
END;


-- Trigger to enforce valid feedback ratings
CREATE TRIGGER ValidateRatingBeforeInsert
BEFORE INSERT ON Registrations
FOR EACH ROW
BEGIN
    IF NEW.feedback_rating NOT BETWEEN 1 AND 10 THEN
        SET NEW.feedback_rating = NULL;
    END IF;
END;

CREATE VIEW EventRevenueView AS
SELECT
    E.event_id,
    E.event_name,
    COUNT(R.registration_id) AS total_tickets_sold,
    (COUNT(R.registration_id) * E.ticket_price) AS total_revenue
FROM Events E
LEFT JOIN Registrations R ON E.event_id = R.event_id
GROUP BY E.event_id, E.event_name, E.ticket_price;

CREATE VIEW UserAttendanceView AS
SELECT
    U.user_id,
    U.name,
    COUNT(CASE WHEN R.attended = TRUE THEN 1 END) AS total_attended,
    ROUND(AVG(R.feedback_rating), 2) AS avg_rating
FROM Users U
LEFT JOIN Registrations R ON U.user_id = R.user_id
GROUP BY U.user_id, U.name;



/******************************************************
     5: EVENT CAPACITY + WAITING LIST SYSTEM
******************************************************/

-- Add capacity and seats counter
ALTER TABLE Events
ADD COLUMN max_capacity INT DEFAULT 100,
ADD COLUMN seats_filled INT DEFAULT 0;

-- Waiting list table
CREATE TABLE WaitingList (
    wait_id BIGINT PRIMARY KEY,
    user_id INT NOT NULL,
    event_id INT NOT NULL,
    request_date DATE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(user_id),
    FOREIGN KEY (event_id) REFERENCES Events(event_id)
);

-- Trigger: If event is full → move to waiting list
CREATE TRIGGER ManageEventCapacity
BEFORE INSERT ON Registrations
FOR EACH ROW
BEGIN
    DECLARE maxCap INT;
    DECLARE filled INT;

    SELECT max_capacity, seats_filled INTO maxCap, filled
    FROM Events
    WHERE event_id = NEW.event_id;

    IF filled >= maxCap THEN
        INSERT INTO WaitingList (wait_id, user_id, event_id, request_date)
        VALUES (UUID_SHORT(), NEW.user_id, NEW.event_id, CURDATE());

        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Event is full. User added to waiting list.';
    ELSE
        UPDATE Events
        SET seats_filled = seats_filled + 1
        WHERE event_id = NEW.event_id;
    END IF;
END;


-- Refund table
CREATE TABLE Refunds (
    refund_id BIGINT PRIMARY KEY,
    registration_id INT,
    user_id INT,
    event_id INT,
    refund_amount DECIMAL(10,2),
    refund_date DATE,
    FOREIGN KEY (registration_id) REFERENCES Registrations(registration_id)
);

-- Soft delete column
ALTER TABLE Events
ADD COLUMN is_cancelled BOOLEAN DEFAULT FALSE;

-- Trigger: When event cancelled → auto refund users
CREATE TRIGGER AutoRefundOnCancellation
AFTER UPDATE ON Events
FOR EACH ROW
BEGIN
    IF NEW.is_cancelled = TRUE AND OLD.is_cancelled = FALSE THEN
        INSERT INTO Refunds (refund_id, registration_id, user_id, event_id, refund_amount, refund_date)
        SELECT UUID_SHORT(), R.registration_id, R.user_id, R.event_id, E.ticket_price, CURDATE()
        FROM Registrations R
        JOIN Events E ON R.event_id = E.event_id
        WHERE R.event_id = NEW.event_id;
    END IF;
END;

/******************************************************
   6: USER LOYALTY POINTS + RECOMMENDATION SYSTEM
******************************************************/

-- Add points column
ALTER TABLE Users
ADD COLUMN points INT DEFAULT 0;

-- Trigger: add points if attendance changes to TRUE
CREATE TRIGGER AddPointsOnAttendance
AFTER UPDATE ON Registrations
FOR EACH ROW
BEGIN
    IF NEW.attended = TRUE AND OLD.attended = FALSE THEN
        UPDATE Users
        SET points = points + 10
        WHERE user_id = NEW.user_id;
    END IF;
END;

-- View: Recommend similar events based on past category
CREATE VIEW RecommendedEvents AS
SELECT DISTINCT
    U.user_id,
    E2.event_name AS recommended_event,
    E2.category
FROM Users U
JOIN Registrations R ON U.user_id = R.user_id
JOIN Events E1 ON R.event_id = E1.event_id
JOIN Events E2 ON E1.category = E2.category
WHERE E2.event_id != E1.event_id;


/******************************************************
     7: ADMIN ACTIVITY LOGS (AUDIT SYSTEM)
******************************************************/

CREATE TABLE AdminLogs (
    log_id BIGINT PRIMARY KEY,
    admin_id INT NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    description TEXT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES Users(user_id)
);

-- Trigger: Log event creation
CREATE TRIGGER LogEventCreate
AFTER INSERT ON Events
FOR EACH ROW
BEGIN
    INSERT INTO AdminLogs (log_id, admin_id, action_type, description)
    VALUES (UUID_SHORT(), NEW.created_by, 'CREATE_EVENT',
            CONCAT('Event created: ', NEW.event_name));
END;

-- Trigger: Log event update
CREATE TRIGGER LogEventUpdate
AFTER UPDATE ON Events
FOR EACH ROW
BEGIN
    INSERT INTO AdminLogs (log_id, admin_id, action_type, description)
    VALUES (UUID_SHORT(), NEW.created_by, 'UPDATE_EVENT',
            CONCAT('Event updated: ', NEW.event_name));
END;


/******************************************************
     8: COUPON AND DISCOUNT SYSTEM
******************************************************/

CREATE TABLE Coupons (
    coupon_id VARCHAR(20) PRIMARY KEY,
    discount_percent INT NOT NULL,
    expiry_date DATE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE
);

ALTER TABLE Registrations
ADD COLUMN coupon_used VARCHAR(20),
ADD COLUMN final_amount DECIMAL(10,2);

-- Trigger: Apply discount on registration
CREATE TRIGGER ApplyCouponDiscount
BEFORE INSERT ON Registrations
FOR EACH ROW
BEGIN
    DECLARE disc INT DEFAULT 0;
    DECLARE price DECIMAL(10,2);

    IF NEW.coupon_used IS NOT NULL THEN
        SELECT discount_percent INTO disc
        FROM Coupons
        WHERE coupon_id = NEW.coupon_used
        AND is_active = TRUE
        AND expiry_date >= CURDATE();

        SELECT ticket_price INTO price
        FROM Events
        WHERE event_id = NEW.event_id;

        SET NEW.final_amount = price - (price * disc / 100);
    ELSE
        SELECT ticket_price INTO price
        FROM Events
        WHERE event_id = NEW.event_id;

        SET NEW.final_amount = price;
    END IF;
END;


/******************************************************
     9: EVENT TAGGING SYSTEM (MANY-TO-MANY)
******************************************************/

CREATE TABLE Tags (
    tag_id INT AUTO_INCREMENT PRIMARY KEY,
    tag_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE EventTags (
    event_id INT NOT NULL,
    tag_id INT NOT NULL,
    PRIMARY KEY (event_id, tag_id),
    FOREIGN KEY (event_id) REFERENCES Events(event_id),
    FOREIGN KEY (tag_id) REFERENCES Tags(tag_id)
);


/******************************************************
     10: MONTHLY REPORT STORED PROCEDURE
******************************************************/

DELIMITER $$

CREATE PROCEDURE GenerateMonthlyReport(IN month_no INT, IN year_no INT)
BEGIN
    SELECT 
        (SELECT COUNT(*) FROM Users WHERE MONTH(created_at)=month_no AND YEAR(created_at)=year_no) AS new_users,
        (SELECT COUNT(*) FROM Registrations WHERE MONTH(registration_date)=month_no AND YEAR(registration_date)=year_no) AS total_registrations,
        (SELECT SUM(final_amount) FROM Registrations WHERE MONTH(registration_date)=month_no AND YEAR(registration_date)=year_no) AS monthly_revenue;
END $$

DELIMITER ;



/******************************************************
     11: NOTIFICATION QUEUE SYSTEM
******************************************************/

CREATE TABLE NotificationQueue (
    notif_id BIGINT PRIMARY KEY,
    user_id INT NOT NULL,
    message TEXT NOT NULL,
    status ENUM('pending', 'sent') DEFAULT 'pending',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(user_id)
);

-- Trigger: Add notification on registration
CREATE TRIGGER NotifyRegistration
AFTER INSERT ON Registrations
FOR EACH ROW
BEGIN
    INSERT INTO NotificationQueue (notif_id, user_id, message)
    VALUES (UUID_SHORT(), NEW.user_id,
            CONCAT('Registration successful for event ID: ', NEW.event_id));
END;


/******************************************************
     12: EVENT ATTENDANCE QR SYSTEM
******************************************************/

CREATE TABLE EventQR (
    qr_id BIGINT PRIMARY KEY,
    event_id INT NOT NULL,
    qr_code TEXT NOT NULL, 
    generated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES Events(event_id)
);

-- QR Scan Log
CREATE TABLE QRScanLog (
    scan_id BIGINT PRIMARY KEY,
    user_id INT NOT NULL,
    event_id INT NOT NULL,
    scanned_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(user_id),
    FOREIGN KEY (event_id) REFERENCES Events(event_id)
);

-- Trigger: Mark attendance when QR scanned
CREATE TRIGGER MarkAttendanceOnQRScan
AFTER INSERT ON QRScanLog
FOR EACH ROW
BEGIN
    UPDATE Registrations
    SET attended = TRUE
    WHERE user_id = NEW.user_id AND event_id = NEW.event_id;
END;


/******************************************************
     13: EVENT RATING & REVIEW MODERATION
******************************************************/

CREATE TABLE EventReviews (
    review_id BIGINT PRIMARY KEY,
    user_id INT,
    event_id INT,
    rating INT CHECK (rating BETWEEN 1 AND 5),
    review_text TEXT,
    is_blocked BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(user_id),
    FOREIGN KEY (event_id) REFERENCES Events(event_id)
);

-- Trigger: block bad words
CREATE TRIGGER BlockBadReview
BEFORE INSERT ON EventReviews
FOR EACH ROW
BEGIN
    IF NEW.review_text REGEXP 'shit|fuck|bitch|abuse|idiot' THEN
        SET NEW.is_blocked = TRUE;
    END IF;
END;


/******************************************************
     14: USER LOGIN HISTORY
******************************************************/

CREATE TABLE LoginHistory (
    login_id BIGINT PRIMARY KEY,
    user_id INT NOT NULL,
    login_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(50),
    device_info VARCHAR(200),
    FOREIGN KEY (user_id) REFERENCES Users(user_id)
);


/******************************************************
     15: EVENT POPULARITY RANKING VIEW
******************************************************/

CREATE VIEW EventPopularity AS
SELECT 
    E.event_id,
    E.event_name,
    COUNT(R.registration_id) AS total_registrations,
    SUM(CASE WHEN R.attended = TRUE THEN 1 ELSE 0 END) AS total_attended,
    (SUM(CASE WHEN R.attended = TRUE THEN 1 ELSE 0 END) / COUNT(R.registration_id)) * 100 AS attendance_percentage
FROM Events E
LEFT JOIN Registrations R ON E.event_id = R.event_id
GROUP BY E.event_id, E.event_name
ORDER BY attendance_percentage DESC;


/******************************************************
     16: BACKUP AND RESTORE SYSTEM
******************************************************/

CREATE TABLE DeletedEventsBackup (
    backup_id BIGINT PRIMARY KEY,
    event_id INT,
    event_name VARCHAR(100),
    deleted_at DATETIME,
    FOREIGN KEY (event_id) REFERENCES Events(event_id)
);

-- Trigger: backup on delete
CREATE TRIGGER BackupDeletedEvent
BEFORE DELETE ON Events
FOR EACH ROW
BEGIN
    INSERT INTO DeletedEventsBackup (backup_id, event_id, event_name, deleted_at)
    VALUES (UUID_SHORT(), OLD.event_id, OLD.event_name, NOW());
END;


/******************************************************
    17: EVENT RECOMMENDATION ENGINE (RULE BASED)
******************************************************/

CREATE VIEW UserEventRecommendations AS
SELECT 
    U.user_id,
    U.name,
    E.category AS recommended_category,
    COUNT(R.registration_id) AS interest_score
FROM Users U
JOIN Registrations R ON U.user_id = R.user_id
JOIN Events E ON R.event_id = E.event_id
WHERE R.attended = TRUE
GROUP BY U.user_id, E.category
ORDER BY interest_score DESC;


/******************************************************
     18: SPAM REGISTRATION DETECTOR
******************************************************/

CREATE TABLE SpamRegistrations (
    spam_id BIGINT PRIMARY KEY,
    user_id INT,
    event_id INT,
    detected_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER DetectSpamRegistration
BEFORE INSERT ON Registrations
FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM Registrations 
        WHERE user_id = NEW.user_id AND event_id = NEW.event_id
    ) THEN
        INSERT INTO SpamRegistrations (spam_id, user_id, event_id)
        VALUES (UUID_SHORT(), NEW.user_id, NEW.event_id);
    END IF;
END;


/******************************************************
      19: REFUND AND CANCELLATION ANALYTICS
******************************************************/

CREATE TABLE Refunds (
    refund_id BIGINT PRIMARY KEY,
    user_id INT,
    event_id INT,
    refund_amount DECIMAL(10,2),
    refunded_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    reason VARCHAR(300),
    FOREIGN KEY (user_id) REFERENCES Users(user_id),
    FOREIGN KEY (event_id) REFERENCES Events(event_id)
);

CREATE VIEW RefundAnalytics AS
SELECT 
    E.event_name,
    COUNT(RF.refund_id) AS total_refunds,
    SUM(RF.refund_amount) AS total_loss
FROM Refunds RF
JOIN Events E ON RF.event_id = E.event_id
GROUP BY E.event_name
ORDER BY total_loss DESC;



/******************************************************
      20: EVENT VERSION HISTORY (AUDIT LOG)
******************************************************/

CREATE TABLE EventHistory (
    history_id BIGINT PRIMARY KEY,
    event_id INT,
    old_name VARCHAR(255),
    old_category VARCHAR(50),
    old_price DECIMAL(10,2),
    changed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES Events(event_id)
);

CREATE TRIGGER LogEventUpdate
BEFORE UPDATE ON Events
FOR EACH ROW
BEGIN
    INSERT INTO EventHistory (history_id, event_id, old_name, old_category, old_price)
    VALUES (UUID_SHORT(), OLD.event_id, OLD.event_name, OLD.category, OLD.ticket_price);
END;


/******************************************************
      21: ORGANIZER PAYOUT SYSTEM
******************************************************/

CREATE TABLE OrganizerPayouts (
    payout_id BIGINT PRIMARY KEY,
    organizer_id INT,
    event_id INT,
    total_revenue DECIMAL(10,2),
    commission_percentage DECIMAL(5,2) DEFAULT 10.0,
    payout_amount DECIMAL(10,2),
    generated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE VIEW OrganizerPayoutView AS
SELECT
    O.organizer_id,
    O.name AS organizer_name,
    E.event_name,
    (COUNT(R.registration_id) * E.ticket_price) AS total_revenue,
    ((COUNT(R.registration_id) * E.ticket_price) * 0.90) AS payout_amount
FROM Organizers O
JOIN Events E ON O.organizer_id = E.organizer_id
JOIN Registrations R ON E.event_id = R.event_id
GROUP BY O.organizer_id, E.event_name;


/******************************************************
    22: USER BADGE & ACHIEVEMENT SYSTEM
******************************************************/

CREATE TABLE UserBadges (
    badge_id BIGINT PRIMARY KEY,
    user_id INT,
    badge_level VARCHAR(20),
    assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(user_id)
);

CREATE VIEW UserBadgeView AS
SELECT 
    U.user_id,
    U.name,
    COUNT(R.registration_id) AS attended_events,
    CASE
        WHEN COUNT(R.registration_id) >= 6 THEN 'Gold'
        WHEN COUNT(R.registration_id) >= 3 THEN 'Silver'
        WHEN COUNT(R.registration_id) >= 1 THEN 'Bronze'
        ELSE 'None'
    END AS badge_level
FROM Users U
LEFT JOIN Registrations R ON U.user_id = R.user_id AND R.attended = TRUE
GROUP BY U.user_id, U.name;


/******************************************************
     23: SMART EVENT CAPACITY SYSTEM
******************************************************/

ALTER TABLE Events
ADD capacity INT DEFAULT 100;

CREATE TRIGGER BlockIfFullCapacity
BEFORE INSERT ON Registrations
FOR EACH ROW
BEGIN
    DECLARE total INT;
    
    SELECT COUNT(*) INTO total
    FROM Registrations
    WHERE event_id = NEW.event_id;
    
    IF total >= (SELECT capacity FROM Events WHERE event_id = NEW.event_id) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Event capacity full. Cannot register.';
    END IF;
END;


/******************************************************
     24: AUTO WAITLIST SYSTEM
******************************************************/

CREATE TABLE Waitlist (
    wait_id BIGINT PRIMARY KEY,
    user_id INT,
    event_id INT,
    added_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER AddToWaitlistIfFull
BEFORE INSERT ON Registrations
FOR EACH ROW
BEGIN
    DECLARE total INT;
    
    SELECT COUNT(*) INTO total
    FROM Registrations
    WHERE event_id = NEW.event_id;
    
    IF total >= (SELECT capacity FROM Events WHERE event_id = NEW.event_id) THEN
        INSERT INTO Waitlist (wait_id, user_id, event_id)
        VALUES (UUID_SHORT(), NEW.user_id, NEW.event_id);
        
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Event full — added to waitlist.';
    END IF;
END;


/******************************************************
     25: DYNAMIC PREDICTIVE EVENT PRICING
******************************************************/

CREATE TABLE PriceHistory (
    record_id BIGINT PRIMARY KEY,
    event_id INT,
    old_price DECIMAL(10,2),
    new_price DECIMAL(10,2),
    changed_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE PROCEDURE UpdateEventPrices()
BEGIN
    INSERT INTO PriceHistory (record_id, event_id, old_price, new_price)
    SELECT 
        UUID_SHORT(),
        E.event_id,
        E.ticket_price,
        (E.ticket_price + (COUNT(R.registration_id) * 0.5))
    FROM Events E
    JOIN Registrations R ON E.event_id = R.event_id
    GROUP BY E.event_id;

    UPDATE Events E
    JOIN (
        SELECT 
            event_id,
            (ticket_price + (COUNT(*) * 0.5)) AS updated_price
        FROM Registrations R
        JOIN Events E2 ON R.event_id = E2.event_id
        GROUP BY event_id
    ) X ON E.event_id = X.event_id
    SET E.ticket_price = X.updated_price;
END;
